from tensorhive.controllers.user.CreateUserController import CreateUserController
from tensorhive.controllers.reservation_event.CreateReservationEventController import CreateReservationEventController


def init_set():
    gpu_list = ['GPU0','GPU1','GPU2','GPU3']

    user_list = [ {'username': 'Kamil Nowodworski'},
                 {'username': 'Tomasz Berezowski'},
                 {'username': 'Kamil Grinholc'},
                 {'username': 'Artur Poliński'},
                 {'username': 'Grzegorz Chlodzinski'},
                 {'username': 'Kamil Szymański'},
                 {'username': 'Paweł Rościszewski'},
                 {'username': 'Jacek Rumiński'},
                 {'username': 'Marcin Knap'}
    ]
    for user in user_list:
        CreateUserController.register(user)

    reservation_events_list = [{'title': 'Attention_ocr + scheduled_sampling' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU0')+1,
                'userId': user_list.count({'username': 'Kamil Nowodworski'})+1,
                'start': '2018-03-16T00:00:00.000Z',
                'end': '2018-03-18T23:59:59.999Z'
                },
                {'title': 'Attention_ocr + scheduled_sampling' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU1')+1,
                'userId': user_list.count({'username': 'Kamil Nowodworski'})+1,
                'start': '2018-03-16T00:00:00.000Z',
                'end': '2018-03-18T23:59:59.999Z'
                },
                {'title': 'Attention_ocr + scheduled_sampling' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU2')+1,
                'userId': user_list.count({'username': 'Kamil Nowodworski'})+1,
                'start': '2018-03-16T00:00:00.000Z',
                'end': '2018-03-18T23:59:59.999Z'
                },
                {'title': 'Attention_ocr + scheduled_sampling' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU3')+1,
                'userId': user_list.count({'username': 'Kamil Nowodworski'})+1,
                'start': '2018-03-16T00:00:00.000Z',
                'end': '2018-03-18T23:59:59.999Z'
                },
                {'title': 'Attention_ocr' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU3')+1,
                'userId': user_list.count({'username': 'Kamil Nowodworski'})+1,
                'start': '2018-05-10T00:00:00.000Z',
                'end': '2018-05-10T23:59:59.999Z'
                },
                {'title': 'PointNet' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU1')+1,
                'userId': user_list.count({'username': 'Kamil Szymański'})+1,
                'start': '2018-05-11T00:00:00.000Z',
                'end': '2018-05-12T23:59:59.999Z'
                },
                {'title': 'DeepRL i DM Lab' ,
                'description': 'Part 1' ,
                'resourceId': gpu_list.count('GPU3')+1,
                'userId': user_list.count({'username': 'Grzegorz Chlodzinski'})+1,
                'start': '2018-05-23T00:00:00.000Z',
                'end': '2018-05-30T23:59:59.999Z'
                },
                {'title': 'DeepRL i DM Lab' ,
                'description': 'Part 2' ,
                'resourceId': gpu_list.count('GPU0')+1,
                'userId': user_list.count({'username': 'Grzegorz Chlodzinski'})+1,
                'start': '2018-05-23T00:00:00.000Z',
                'end': '2018-05-30T23:59:59.999Z'
                },
                {'title': 'DeepRL i DM Lab' ,
                'description': 'Part 2' ,
                'resourceId': gpu_list.count('GPU1')+1,
                'userId': user_list.count({'username': 'Grzegorz Chlodzinski'})+1,
                'start': '2018-05-23T00:00:00.000Z',
                'end': '2018-05-30T23:59:59.999Z'
                },
                {'title': 'DeepRL i DM Lab' ,
                'description': 'Part 3' ,
                'resourceId': gpu_list.count('GPU0')+1,
                'userId': user_list.count({'username': 'Grzegorz Chlodzinski'})+1,
                'start': '2018-05-31T00:00:00.000Z',
                'end': '2018-06-03T23:59:59.999Z'
                },
                {'title': 'DeepRL i DM Lab' ,
                'description': 'Part 3' ,
                'resourceId': gpu_list.count('GPU1')+1,
                'userId': user_list.count({'username': 'Grzegorz Chlodzinski'})+1,
                'start': '2018-05-31T00:00:00.000Z',
                'end': '2018-06-03T23:59:59.999Z'
                },
                {'title': 'Prezentacja dla koła Gradient, distributed GAN' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU0')+1,
                'userId': user_list.count({'username': 'Paweł Rościszewski'})+1,
                'start': '2018-06-05T00:00:00.000Z',
                'end': '2018-06-06T23:59:59.999Z'
                },
                {'title': 'Prezentacja dla koła Gradient, distributed GAN' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU1')+1,
                'userId': user_list.count({'username': 'Paweł Rościszewski'})+1,
                'start': '2018-06-05T00:00:00.000Z',
                'end': '2018-06-06T23:59:59.999Z'
                },
                {'title': 'Prezentacja dla koła Gradient, distributed GAN' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU2')+1,
                'userId': user_list.count({'username': 'Paweł Rościszewski'})+1,
                'start': '2018-06-05T00:00:00.000Z',
                'end': '2018-06-06T23:59:59.999Z'
                },
                {'title': 'Prezentacja dla koła Gradient, distributed GAN' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU3')+1,
                'userId': user_list.count({'username': 'Paweł Rościszewski'})+1,
                'start': '2018-06-05T00:00:00.000Z',
                'end': '2018-06-06T23:59:59.999Z'
                },
                {'title': 'attention_ocr+bidirectional_lstm+sigmoidal_sampling' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU0')+1,
                'userId': user_list.count({'username': 'Kamil Nowodworski'})+1,
                'start': '2018-06-05T00:00:00.000Z',
                'end': '2018-06-06T23:59:59.999Z'
                },
                {'title': 'attention_ocr+bidirectional_lstm+sigmoidal_sampling' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU1')+1,
                'userId': user_list.count({'username': 'Kamil Nowodworski'})+1,
                'start': '2018-06-05T00:00:00.000Z',
                'end': '2018-06-06T23:59:59.999Z'
                },
                {'title': 'Modyfikacja Mobile Net' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU2')+1,
                'userId': user_list.count({'username': 'Kamil Grinholc'})+1,
                'start': '2018-06-10T00:00:00.000Z',
                'end': '2018-06-12T23:59:59.999Z'
                },
                {'title': 'Modyfikacja Mobile Net' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU3')+1,
                'userId': user_list.count({'username': 'Kamil Grinholc'})+1,
                'start': '2018-06-10T00:00:00.000Z',
                'end': '2018-06-12T23:59:59.999Z'
                },
                {'title': 'Szkola letnia' ,
                'description': 'SERWER ZAREZEROWANY DLA PRAC ZWIĄZANYCH ZE SZKOŁĄ LETNIA!!!' ,
                'resourceId': gpu_list.count('GPU0')+1,
                'userId': user_list.count({'username': 'Jacek Rumiński'})+1,
                'start': '2018-06-20T00:00:00.000Z',
                'end': '2018-07-07T23:59:59.999Z'
                },
                {'title': 'Szkola letnia' ,
                'description': 'SERWER ZAREZEROWANY DLA PRAC ZWIĄZANYCH ZE SZKOŁĄ LETNIA!!!' ,
                'resourceId': gpu_list.count('GPU1')+1,
                'userId': user_list.count({'username': 'Jacek Rumiński'})+1,
                'start': '2018-06-20T00:00:00.000Z',
                'end': '2018-07-07T23:59:59.999Z'
                },
                {'title': 'Szkola letnia' ,
                'description': 'SERWER ZAREZEROWANY DLA PRAC ZWIĄZANYCH ZE SZKOŁĄ LETNIA!!!' ,
                'resourceId': gpu_list.count('GPU2')+1,
                'userId': user_list.count({'username': 'Jacek Rumiński'})+1,
                'start': '2018-06-20T00:00:00.000Z',
                'end': '2018-07-07T23:59:59.999Z'
                },
                {'title': 'Szkola letnia' ,
                'description': 'SERWER ZAREZEROWANY DLA PRAC ZWIĄZANYCH ZE SZKOŁĄ LETNIA!!!' ,
                'resourceId': gpu_list.count('GPU3')+1,
                'userId': user_list.count({'username': 'Jacek Rumiński'})+1,
                'start': '2018-06-20T00:00:00.000Z',
                'end': '2018-07-07T23:59:59.999Z'
                },
                {'title': 'Szkola letnia' ,
                'description': 'SERWER ZAREZEROWANY DLA PRAC ZWIĄZANYCH ZE SZKOŁĄ LETNIA!!!' ,
                'resourceId': gpu_list.count('GPU0')+1,
                'userId': user_list.count({'username': 'Jacek Rumiński'})+1,
                'start': '2018-06-20T00:00:00.000Z',
                'end': '2018-07-07T23:59:59.999Z'
                },
                {'title': 'Szkola letnia' ,
                'description': 'SERWER ZAREZEROWANY DLA PRAC ZWIĄZANYCH ZE SZKOŁĄ LETNIA!!!' ,
                'resourceId': gpu_list.count('GPU1')+1,
                'userId': user_list.count({'username': 'Jacek Rumiński'})+1,
                'start': '2018-06-20T00:00:00.000Z',
                'end': '2018-07-07T23:59:59.999Z'
                },
                {'title': 'Szkola letnia' ,
                'description': 'SERWER ZAREZEROWANY DLA PRAC ZWIĄZANYCH ZE SZKOŁĄ LETNIA!!!' ,
                'resourceId': gpu_list.count('GPU2')+1,
                'userId': user_list.count({'username': 'Jacek Rumiński'})+1,
                'start': '2018-06-20T00:00:00.000Z',
                'end': '2018-07-07T23:59:59.999Z'
                },
                {'title': 'Szkola letnia' ,
                'description': 'SERWER ZAREZEROWANY DLA PRAC ZWIĄZANYCH ZE SZKOŁĄ LETNIA!!!' ,
                'resourceId': gpu_list.count('GPU3')+1,
                'userId': user_list.count({'username': 'Jacek Rumiński'})+1,
                'start': '2018-06-20T00:00:00.000Z',
                'end': '2018-07-07T23:59:59.999Z'
                },
                {'title': 'Dokończenie ostatniego eksperymentu' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU0')+1,
                'userId': user_list.count({'username': 'Kamil Nowodworski'})+1,
                'start': '2018-07-08T00:00:00.000Z',
                'end': '2018-07-12T23:59:59.999Z'
                },
                {'title': 'Eksperymenty z DeepRL' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU2')+1,
                'userId': user_list.count({'username': 'Grzegorz Chlodzinski'})+1,
                'start': '2018-07-08T00:00:00.000Z',
                'end': '2018-07-13T23:59:59.999Z'
                },
                {'title': 'Eksperymenty z DeepRL' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU3')+1,
                'userId': user_list.count({'username': 'Grzegorz Chlodzinski'})+1,
                'start': '2018-07-08T00:00:00.000Z',
                'end': '2018-07-13T23:59:59.999Z'
                },
                {'title': 'Eksperymenty z DeepRL' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU0')+1,
                'userId': user_list.count({'username': 'Grzegorz Chlodzinski'})+1,
                'start': '2018-07-14T00:00:00.000Z',
                'end': '2018-07-22T23:59:59.999Z'
                },
                {'title': 'Eksperymenty z DeepRL' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU1')+1,
                'userId': user_list.count({'username': 'Grzegorz Chlodzinski'})+1,
                'start': '2018-07-14T00:00:00.000Z',
                'end': '2018-07-22T23:59:59.999Z'
                },
                {'title': 'Attention_ocr+bidirectional_lstm+sigmoidal_sampling' ,
                'description': 'Dokończenie ostatniego eksperymentu przerwanego przez brak dostępu' ,
                'resourceId': gpu_list.count('GPU2')+1,
                'userId': user_list.count({'username': 'Kamil Nowodworski'})+1,
                'start': '2018-07-14T00:00:00.000Z',
                'end': '2018-07-20T23:59:59.999Z'
                },
                {'title': 'Attention_ocr+bidirectional_lstm+sigmoidal_sampling' ,
                'description': 'Dokończenie ostatniego eksperymentu przerwanego przez brak dostępu' ,
                'resourceId': gpu_list.count('GPU3')+1,
                'userId': user_list.count({'username': 'Kamil Nowodworski'})+1,
                'start': '2018-07-14T00:00:00.000Z',
                'end': '2018-07-20T23:59:59.999Z'
                },
                {'title': 'Powtórka wyników bidirectional LSTM + attention_ocr' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU2')+1,
                'userId': user_list.count({'username': 'Kamil Nowodworski'})+1,
                'start': '2018-07-21T00:00:00.000Z',
                'end': '2018-08-11T23:59:59.999Z'
                },
                {'title': 'Powtórka wyników bidirectional LSTM + attention_ocr' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU3')+1,
                'userId': user_list.count({'username': 'Kamil Nowodworski'})+1,
                'start': '2018-07-21T00:00:00.000Z',
                'end': '2018-08-11T23:59:59.999Z'
                },
                {'title': 'Eksperymenty z DeepRL GPU0' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU0')+1,
                'userId': user_list.count({'username': 'Grzegorz Chlodzinski'})+1,
                'start': '2018-07-23T00:00:00.000Z',
                'end': '2018-07-29T23:59:59.999Z'
                },
                {'title': 'Eksperymenty z DeepRL GPU0' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU1')+1,
                'userId': user_list.count({'username': 'Grzegorz Chlodzinski'})+1,
                'start': '2018-07-23T00:00:00.000Z',
                'end': '2018-07-29T23:59:59.999Z'
                },
                {'title': 'Powtórka wyników bidirectional LSTM + attention_ocr' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU1')+1,
                'userId': user_list.count({'username': 'Kamil Nowodworski'})+1,
                'start': '2018-07-30T00:00:00.000Z',
                'end': '2018-08-11T23:59:59.999Z'
                },
                {'title': 'Testy mixed precision training na DeepSpeech' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU0')+1,
                'userId': user_list.count({'username': 'Paweł Rościszewski'})+1,
                'start': '2018-07-30T00:00:00.000Z',
                'end': '2018-08-03T23:59:59.999Z'
                },
                {'title': 'Modyfikacja Mobile Net, LSTM' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU0')+1,
                'userId': user_list.count({'username': 'Kamil Grinholc'})+1,
                'start': '2018-08-04T00:00:00.000Z',
                'end': '2018-08-05T23:59:59.999Z'
                },
                {'title': 'Testy UM, INT8, FL16' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU0')+1,
                'userId': user_list.count({'username': 'Marcin Knap'})+1,
                'start': '2018-08-06T00:00:00.000Z',
                'end': '2018-08-07T23:59:59.999Z'
                },
                {'title': 'Modyfikacja Mobile Net, LSTM' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU0')+1,
                'userId': user_list.count({'username': 'Kamil Grinholc'})+1,
                'start': '2018-08-08T00:00:00.000Z',
                'end': '2018-08-13T23:59:59.999Z'
                },
                {'title': 'Attention_ocr bez bidirectional LSTM' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU1')+1,
                'userId': user_list.count({'username': 'Kamil Nowodworski'})+1,
                'start': '2018-08-11T00:00:00.000Z',
                'end': '2018-08-21T23:59:59.999Z'
                },
                {'title': 'Attention_ocr bez bidirectional LSTM' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU2')+1,
                'userId': user_list.count({'username': 'Kamil Nowodworski'})+1,
                'start': '2018-08-11T00:00:00.000Z',
                'end': '2018-08-21T23:59:59.999Z'
                },
                {'title': 'Attention_ocr bez bidirectional LSTM' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU3')+1,
                'userId': user_list.count({'username': 'Kamil Nowodworski'})+1,
                'start': '2018-08-11T00:00:00.000Z',
                'end': '2018-08-21T23:59:59.999Z'
                },
                {'title': 'Testy multigpu na DeepSpeech' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU0')+1,
                'userId': user_list.count({'username': 'Paweł Rościszewski'})+1,
                'start': '2018-08-22T00:00:00.000Z',
                'end': '2018-08-24T23:59:59.999Z'
                },
                {'title': 'Testy multigpu na DeepSpeech' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU1')+1,
                'userId': user_list.count({'username': 'Paweł Rościszewski'})+1,
                'start': '2018-08-22T00:00:00.000Z',
                'end': '2018-08-24T23:59:59.999Z'
                },
                {'title': 'Testy multigpu na DeepSpeech' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU2')+1,
                'userId': user_list.count({'username': 'Paweł Rościszewski'})+1,
                'start': '2018-08-22T00:00:00.000Z',
                'end': '2018-08-24T23:59:59.999Z'
                },
                {'title': 'Testy multigpu na DeepSpeech' ,
                'description': '' ,
                'resourceId': gpu_list.count('GPU3')+1,
                'userId': user_list.count({'username': 'Paweł Rościszewski'})+1,
                'start': '2018-08-22T00:00:00.000Z',
                'end': '2018-08-24T23:59:59.999Z'
                },
                {'title': 'Attention_ocr' ,
                'description': 'Dokończenie' ,
                'resourceId': gpu_list.count('GPU2')+1,
                'userId': user_list.count({'username': 'Kamil Nowodworski'})+1,
                'start': '2018-08-25T00:00:00.000Z',
                'end': '2018-09-09T23:59:59.999Z'
                },
                {'title': 'Attention_ocr' ,
                'description': 'Dokończenie' ,
                'resourceId': gpu_list.count('GPU3')+1,
                'userId': user_list.count({'username': 'Kamil Nowodworski'})+1,
                'start': '2018-08-25T00:00:00.000Z',
                'end': '2018-09-09T23:59:59.999Z'
                }
    ]

    for reservation_event in reservation_events_list:
        CreateReservationEventController.create(reservation_event)