swagger: "2.0"

info:
  title: "{{title}} v{{version}}"
  version: "{{version}}"

basePath: "/v{{version}}"

paths:
  /users:
    get:
      tags: 
        - users
      summary: Get all users
      responses:
        '200':
          description: 'All fetched with success.'
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      tags: 
        - users
      summary: Create new user
      parameters:
        - in: body
          name: user
          required: true
          schema:
            $ref: '#/definitions/CreateUserController'
      responses:
        '201':
          description: 'Successfully created.'
        '409':
          description: 'Duplication error.'
        '500':
          description: 'Not registered due to an error.'
  /reservations:
    get:
      tags: 
        - reservations
      summary: Get all reservation events
      responses:
        '200':
          description: 'All fetched with success.'
          schema:
            type: array
            items:
              $ref: '#/definitions/ReservationEvent'
    post:
      tags: 
        - reservations
      summary: Create new reservation event
      parameters:
        - in: body
          name: reservation_event
          required: True
          schema:
            $ref: '#/definitions/CreateReservationEventController'
      responses:
        '201':
          description: 'Successfully created.'
        '500':
          description: 'Not created due to an error.'
  '/reservations/{id}':
    delete:
      tags: 
          - reservations
      summary: Delete reservation event by id
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        '204':
          description: 'Successfully deleted.'
        '404':
          description: 'Not found.'
  # TODO Nodes: Add more specific schemas, response codes + descriptions
  /nodes/hostnames:
    get:
      tags: 
        - nodes
      summary: Get all hostnames
      operationId: 'tensorhive.api.api.nodes.get_hostnames'
      responses:
        '200':
          description: 'List of hostnames fetched with success'
          schema:
            type: array
            items: 
              type: string
  /nodes/metrics:
    get:
      tags: 
        - nodes
      summary: Get all metrics for each node
      operationId: 'tensorhive.api.api.nodes.get_all_metrics'
      responses:
        '200':
          description: 'All metrics fetched with success.'
          schema:
            type: object
  /nodes/{hostname}/metrics/gpu:
    get:
      tags: 
        - nodes
      summary: Get GPU metrics for node with given id
      operationId: 'tensorhive.api.api.nodes.get_gpu_metrics'
      parameters:
        - in: path
          name: hostname
          required: true
          type: string
      responses:
        '200':
          description: 'List of GPU(s) metrics fetched with success.'
          schema:
            type: array
            items: 
              type: object
        '404':
          description: 'Not found.' 
  /nodes/{hostname}/metrics/gpu/fan:
    get:
      tags: 
        - nodes
      summary: TODO
      operationId: 'tensorhive.api.api.nodes.get_gpu_fan'
      parameters:
        - in: path
          name: hostname
          required: true
          type: string
      responses:
        '200':
          description: TODO
          schema:
            type: integer
        '404':
          description: 'Not found.' 
  
definitions:
  CreateUserController:
    type: object
    properties:
      username: { type: string }
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username: { type: string }
      createdAt:
        type: string
        format: date-time
  CreateReservationEventController:
    type: object
    properties:
      title: { type: string }
      description: { type: string }
      nodeId: { type: integer}
      userId: { type: integer}
      start:
        type: string
        format: date-time
      end:
        type: string
        format: date-time
      # TODO Add user id, node id
  ReservationEvent:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title: { type: string }
      description: { type: string }
      nodeId: { type: integer}
      userId: { type: integer}
      start:
        type: string
        format: date-time
      end:
        type: string
        format: date-time
      createdAt:
        type: string
        format: date-time
      # TODO Add user id, node id
