version: 2.1

orbs:
  python: circleci/python@1.4.0

workflows:
  test:
    jobs:
      - test:
          name: "python3.8"
          version: "3.8"
      - test:
          name: "python3.9"
          version: "3.9"
      - test:
          name: "python3.10"
          version: "3.10"

jobs:
  test:
    parameters:
      version:
        type: string
    docker:
      - image: circleci/python:<<parameters.version>>
    steps:      
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-dev.txt
      - run:
          name: Run mypy checks
          command: mypy -p tensorhive -p tests
      - run:
          name: Run flake8 checks
          command: python -m flake8 tensorhive tests
      - python/install-packages:
          pkg-manager: pip-dist
      - run:
          name: Run tests
          command: pytest
