"""Add summary fields to Reservation

Revision ID: bffd7d81d326
Revises: ce624ab2c458
Create Date: 2019-02-21 20:48:59.993973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bffd7d81d326'
down_revision = 'ce624ab2c458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('gpu_util_avg', sa.Integer(), nullable=True))
    op.add_column('reservations', sa.Column('mem_util_avg', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'mem_util_avg')
    op.drop_column('reservations', 'gpu_util_avg')
    # ### end Alembic commands ###
