"""Add email column to User

Revision ID: 05eca1c82f14
Revises: ce624ab2c458
Create Date: 2019-01-29 22:31:48.215468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05eca1c82f14'
down_revision = 'ce624ab2c458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), server_default='<email_missing>', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
