"""empty message

Revision ID: e932b16ad5e3
Revises: 040d8d5fc7bc
Create Date: 2018-10-18 23:46:48.620720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e932b16ad5e3'
down_revision = '040d8d5fc7bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('siema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('siema', sa.VARCHAR(length=40), nullable=True))
    # ### end Alembic commands ###
